config/routes.rb
MyBlog::Application.routes.draw do
  resources :options

  resources :categories

  resources :entries
  root to: 'entries#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :entries
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :category
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :entry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @entry = Entry.new
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :prepare_categories 
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
    @categories = Category.all
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:category_id, :title, :entry)
    end

    # add the @categories = category.All to the before action so avail for all actions

    private

    def prepare_categories
      @categories = Category.all
    end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render action: 'show', status: :created, location: @option }
      else
        format.html { render action: 'new' }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      
  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Category Name:
  = @category.name

%p
  %b Entries:
  - @category.entries.each do |entry|
    %br/
    = entry.title

%p
  %strong Add a new entry:
= form_for @entry do |f|
  = f.hidden_field :category_id, :value => @category.id
  = f.label :title, 'Title'
  \: #{f.text_field :title}
  %br/
  = f.label :entry, 'Entry'
  \: #{f.text_field :entry}
  %br/
  = f.submit 'Add Entry'

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :entry %><br>
    <%= f.text_area :entry %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/_form.html.haml
= form_for @entry do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, "error")} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :category
    = collection_select(:entry, :category_id, @categories, :id, :name, {:prompt => false})
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :entry
    = f.text_area :entry
  .field
    = f.label :options
    = collection_check_boxes(:option, :option_id, Option.all, :id, :name)
  .actions
    = f.submit 'Save'

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', @entry
\|
= link_to 'Back', entries_path

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Entry</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.title %></td>
        <td><%= entry.entry %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/index.html.haml
.page-header
  %h1 Listing Entries
= link_to "Post a New Entry", new_entry_path, class: "btn btn-success"
- @entries.each do |entry|
  .entry
    %strong= entry.title
    %p= entry.entry
    .meta
      = link_to time_ago_in_words(entry.created_at) + " ago", entry
      %span.admin
        | #{link_to "Edit", edit_entry_path(entry)} |
        \#{link_to "Delete", entry, method: :delete, data: {confirm: "Are you sure you want to delete this entry?"}}

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/new.html.haml
%h1 New entry

= render 'form'

= link_to 'Back', entries_path

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @entry.entry %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/entries/show.html.haml
%p#notice= notice

%p
  %b Category:
  = @entry.category.name
%p
  %b Title:
  = @entry.title
%p
  %b Entry:
  = @entry.entry

= link_to 'Edit', edit_entry_path(@entry)
\|
= link_to 'Back', entries_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a hreff="#" class="brand" href="#">MyBlog</a>
			<ul class="nav">
				<li><%= link_to "Entries", entries_path %></li>
		</div>
	</div>
</div>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title myBlog
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand{:href => "#"} myBlog
          %ul.nav
            %li= link_to "Categories", categories_path
            %li= link_to "Entries", entries_path
    .container
      = yield

app/views/options/_form.html.haml
= form_for @option do |f|
  - if @option.errors.any?
    #error_explanation
      %h2= "#{pluralize(@option.errors.count, "error")} prohibited this option from being saved:"
      %ul
        - @option.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/options/edit.html.haml
%h1 Editing option

= render 'form'

= link_to 'Show', @option
\|
= link_to 'Back', options_path

app/views/options/index.html.haml
%h1 Listing options

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      
  %tbody
    - @options.each do |option|
      %tr
        %td= option.name
        %td= link_to 'Show', option
        %td= link_to 'Edit', edit_option_path(option)
        %td= link_to 'Destroy', option, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Option', new_option_path

app/views/options/new.html.haml
%h1 New option

= render 'form'

= link_to 'Back', options_path

app/views/options/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @option.name

= link_to 'Edit', edit_option_path(@option)
\|
= link_to 'Back', options_path